#!/bin/bash
# Delay start prevents some scripts NOT from starting
sleep 5

# Obtener la latitud y longitud de la ubicación actual
lat=$(curl -s http://ip-api.com/line/?fields=lat)
long=$(curl -s http://ip-api.com/line/?fields=lon)

# Función para obtener la hora de anochecer, modificar lat y long en base a tu propia ubicación
get_sunset_utc() {
    curl -s "https://api.sunrise-sunset.org/json?lat=$lat&lng=$long&formatted=0" | jq -r '.results.sunset' | cut -c 12-16
}

sunset_time_utc=$(get_sunset_utc)
sunset_time=$(date -d "$sunset_time_utc UTC" +"%H:%M")

# El formato es HH:MM por lo que formateamos dos variables para que puedan entrar en cron
sunset_hour=$(cut -c 1-2 <<<"$sunset_time")
sunset_min=$(cut -c 4-5 <<<"$sunset_time")

# Crear la línea que se agregará al archivo crontab
# nota """DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus""" 
# La variable DBUS_SESSION_BUS_ADDRESS es necesaria porque los scripts de crontab no se ejecutan como un usuario con sesión iniciada.
cron_line="$sunset_min $sunset_hour * * * DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus /usr/local/bin/DayOrNight"

# Borrar crontab anterior !!PELIGRO
crontab -r

# Definir las variables de entorno necesarias
CONSOLA="SHELL=/bin/bash"
RUTAS="PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
HOM="HOME="$HOME

# En caso de una sesion anterior puede ser que el archivo tmp exista y duplique la cabecera. Nos lo calzamos
rm /tmp/crontab.tmp


# Agregar las nuevas líneas al inicio del archivo temporal
echo "$CONSOLA" >> /tmp/crontab.tmp
echo "$RUTAS" >> /tmp/crontab.tmp
echo "$HOM" >> /tmp/crontab.tmp

# Establecer el crontab modificado
crontab /tmp/crontab.tmp

# Agregar la línea al archivo crontab, puede ser interesante añadir estas lineas si arriba en el codigo si el fichero ya existe.
(crontab -l 2>/dev/null; echo "$cron_line") | crontab -

#Comprobación
notify-send "Sunset at: $sunset_time."
crontab -l





